revert gradle to previously working state
Currently, the android tests with throw a warning "WARNING: Failed to retrieve additional test outputs from device.
com.android.ddmlib.SyncException: Remote object doesn't exist!"
However, trying to fix this by upgrading Gradle and AGP will break all tests with an obscure error that I have spent hours trying to fix. Therefore the best solution is to just ignore this warning